metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true

xpack.monitoring.enabled: false

output.logstash:
  hosts: ["logstash:5000"]

logging.to_files: false
logging.to_syslog: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true