FROM ubuntu:16.04

MAINTAINER Khanh Nguyen <khanhnv.uit@gmail.com>

ENV LC_ALL=C.UTF-8

RUN apt-get update && \
	apt-get -y install wget \
	curl \
	git \
	software-properties-common \
	python-software-properties \
	debian-archive-keyring \
	mcrypt

RUN add-apt-repository ppa:ondrej/php
RUN apt-get update && apt-get -y install \
	vim \
	python \
    python-dev \
    ca-certificates \
    dialog \
    gcc \
    musl-dev \
    libffi-dev \
    python-pip \
    zip \
    unzip \
    iputils-ping \
    build-essential nghttp2 libnghttp2-dev libssl-dev re2c

# Build openssl 1.1.0g
RUN wget https://www.openssl.org/source/openssl-1.1.0g.tar.gz && \
	tar xzvf openssl-1.1.0g.tar.gz && \
	cd openssl-1.1.0g && \
	./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' && \
	make && make install && \
	cd ../ && rm -rf openssl-1.1.0g.tar.gz openssl-1.1.0g

# Build Curl with enable nghttp2
RUN wget https://curl.haxx.se/download/curl-7.55.1.tar.bz2 && \
	tar -xvjf curl-7.55.1.tar.bz2 && \
	cd curl-7.55.1 && \
	./configure --with-nghttp2 --prefix=/usr/local --with-ssl && \
	make && make install && ldconfig && \
	cd ../ && rm -rf curl-7.55.1.tar.bz2 curl-7.55.1

# Install PHP7.0
RUN	apt-get update && apt-get -y install php7.1 php7.1-cgi php7.1-cli php7.1-common php7.1-curl php7.1-dev php7.1-gd php7.1-json php7.1-ldap php7.1-mysql \
	php7.1-odbc php7.1-opcache php7.1-pspell php7.1-readline php7.1-recode php7.1-sqlite3 php7.1-xml libphp7.1-embed php7.1-bcmath \
	php7.1-bz2 php7.1-fpm php7.1-imap php7.1-intl php7.1-mbstring php7.1-xsl php7.1-zip php7.1-dba php-redis php7.1-mongodb php-pear php7.1-mcrypt php7.1-soap php7.1-imagick

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ && mv /usr/bin/composer.phar /usr/bin/composer

# Install Supervisor
RUN apt-get -y install supervisor
RUN mkdir -p /var/log/cache


# Install composer speed
RUN composer global require hirak/prestissimo
RUN composer global require "fxp/composer-asset-plugin:~1.3"

RUN	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN update-alternatives --set php /usr/bin/php7.1

ADD ./php/www.conf /etc/php/7.1/fpm/pool.d/www.conf
ADD ./php/php.ini /etc/php/7.1/fpm/php.ini
ADD ./php/php-fpm.conf /etc/php/7.1/fpm/php-fpm.conf
ADD ./supervisor/supervisord.conf /etc/supervisor/supervisord.conf
RUN curl -O https://pecl.php.net/get/xdebug-2.7.0.tgz \
    && tar -xf xdebug-2.7.0.tgz \
    && cd xdebug-2.7.0 \
    && phpize && ./configure && make && make install \
    && echo "zend_extension=$(find /usr/lib/php/20160303/ -name xdebug.so)"> /etc/php/7.1/mods-available/xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /etc/php/7.1/mods-available/xdebug.ini \ 
    && echo "xdebug.remote_autostart=1" >> /etc/php/7.1/mods-available/xdebug.ini \ 
    && echo "xdebug.remote_host=172.17.0.1" >> /etc/php/7.1/mods-available/xdebug.ini \
    && echo "xdebug.idekey=PHPSTORM" >> /etc/php/7.1/mods-available/xdebug.ini \ 
    && cp /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/fpm/conf.d/ \ 
    && cp /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/cli/conf.d/ \ 
    && cp /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/cgi/conf.d/ \ 
    && cp /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/fpm/conf.d/

EXPOSE 9001
EXPOSE 4200

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
