filebeat.registry_file: /usr/share/filebeat/data/registry

filebeat.config.inputs:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false

#filebeat.prospectors:
#- type: log
#  paths:
#  - "/var/lib/docker/containers/*/*.log"
#  json.message_key: log
#  json.keys_under_root: true
#  processors:
#  - add_docker_metadata: ~

filebeat.modules:

#Filebeat system module consumes logs from host OS through a mounted volume.
- module: system
  syslog:
    var.paths: ["/var/log/syslog"]

#nginx Module consumes access and error logs from mounted volume.
#- module: nginx
#  access:
#    var.paths: ["/var/log/nginx/access*.log*"]
#  error:
#    var.paths: ["/var/log/nginx/error*.log*"]

#MySQL module consumes error and mysql-slow logs from mounted volume.
- module: mysql
  error:
    var.paths: ["/var/log/mysql/error.log*"]
  slowlog:
    var.paths: ["/var/log/mysql/mysql-slow.log*"]

xpack.monitoring.enabled: false

output.logstash:
  hosts: ["logstash:5000"]

logging.to_files: false

setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true