FROM ubuntu:16.04

MAINTAINER Khanh Nguyen <khanhnv.uit@gmail.com>

ENV LC_ALL=C.UTF-8

RUN apt-get update && apt-get -y install wget curl git software-properties-common

RUN add-apt-repository ppa:ondrej/php
RUN apt-get update && apt-get -y install \
		vim \
		make \
		libpcre3-dev \
		python \
	    python-dev \
	    ca-certificates \
	    dialog \
	    gcc \
	    musl-dev \
	    libffi-dev \
	    supervisor \
	    python-pip \
	    iputils-ping

# Install PHP5.6
RUN	apt-get -y install php5.6-dev php5.6-fpm php5.6-mysqlnd php5.6-curl php5.6-gd php-pear php5.6-imagick \
	php5.6-imap php5.6-mcrypt php5.6-intl php5.6-pspell php5.6-recode php5.6-snmp php5.6-tidy php5.6-xmlrpc \
	php5.6-xsl php5.6-xdebug php5.6-redis php5.6-igbinary php5.6-mbstring php-amqp php5.6-bcmath php5.6-mongo php5.6-zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ && mv /usr/bin/composer.phar /usr/bin/composer

# Install Supervisor
RUN apt-get -y install supervisor
RUN mkdir -p /var/log/cache

# Install composer speed
# RUN composer global require hirak/prestissimo

# Install Phalcon
RUN curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | bash
RUN apt-get update && apt-get install php5.6-phalcon

RUN	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN update-alternatives --set php /usr/bin/php5.6

ADD ./php/www.conf /etc/php/5.6/fpm/pool.d/www.conf
ADD ./php/php.ini /etc/php/5.6/fpm/php.ini
ADD ./php/php-fpm.conf /etc/php/5.6/fpm/php-fpm.conf
ADD ./supervisor/supervisord.conf /etc/supervisor/supervisord.conf

EXPOSE 9005

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]