---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
elasticsearch.url: http://elastic:9200
server.host: "0.0.0.0"
xpack.monitoring.ui.container.elasticsearch.enabled: false